# Generated by Django 5.0 on 2024-01-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='devices_quantity',
        ),
        migrations.AddField(
            model_name='room',
            name='fan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='heater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player',
            field=models.BooleanField(default=False),
        ),
    ]
