# Generated by Django 5.0 on 2024-01-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_room_devices_quantity_room_fan_room_heater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='devices_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
