# Generated by Django 5.0 on 2024-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_room_devices_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
