# Generated by Django 5.0 on 2024-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_room_humidity_room_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='voltage',
            field=models.IntegerField(default=0),
        ),
    ]
